services:
  - name: builder-nextjs-app
    git:
      repository: github.com/TeddyJubu/builder
      branch: main
      workdir: /examples/next-js-simple
    instance_type: nano
    ports:
      - port: 8000
        protocol: http
    env:
      - key: PORT
        value: "8000"
      - key: NODE_ENV
        value: production
      - key: BUILDER_PUBLIC_KEY
        scope: secret
    healthcheck:
      http:
        path: /
    build:
      docker:
        dockerfile: Dockerfile
    scaling:
      min: 1
      max: 3